// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsmxBXS5ALDIqzrAc6rbB0y7sF97f2m6A',
    appId: '1:713470530429:web:6ae14414ce3bdd7646b214',
    messagingSenderId: '713470530429',
    projectId: 'allegro-saludable',
    authDomain: 'allegro-saludable.firebaseapp.com',
    storageBucket: 'allegro-saludable.appspot.com',
    measurementId: 'G-RDXSBWZXXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAna8Uf9q6WXsmxfuAyKZd_RU6hpf6IPvk',
    appId: '1:713470530429:android:b105c8bebd933fd946b214',
    messagingSenderId: '713470530429',
    projectId: 'allegro-saludable',
    storageBucket: 'allegro-saludable.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0sAi_XdULY6tvCQoHcl7EQdsYbAAP68Y',
    appId: '1:713470530429:ios:8a20ef5c5c87a7ac46b214',
    messagingSenderId: '713470530429',
    projectId: 'allegro-saludable',
    storageBucket: 'allegro-saludable.appspot.com',
    iosClientId: '713470530429-k28lunprfn8o8jh34c2ik11p5m9kpmie.apps.googleusercontent.com',
    iosBundleId: 'com.vaporgraphic.apps',
  );
}
